<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-action-results.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.ActionStatus
 */
class ActionStatus extends \Protobuf\Enum
{

    /**
     * failureGeneric = 0
     */
    const failureGeneric_VALUE = 0;

    /**
     * success = 1
     */
    const success_VALUE = 1;

    /**
     * deviceNotFound = 2
     */
    const deviceNotFound_VALUE = 2;

    /**
     * apNotFound = 3
     */
    const apNotFound_VALUE = 3;

    /**
     * actionTimeout = 4
     */
    const actionTimeout_VALUE = 4;

    /**
     * connectionAborted = 5
     */
    const connectionAborted_VALUE = 5;

    /**
     * authenticationFailed = 6
     */
    const authenticationFailed_VALUE = 6;

    /**
     * notConnected = 7
     */
    const notConnected_VALUE = 7;

    /**
     * previousActionFailed = 8
     */
    const previousActionFailed_VALUE = 8;

    /**
     * alreadyConnected = 9
     */
    const alreadyConnected_VALUE = 9;

    /**
     * noMoreConnectionSlots = 10
     */
    const noMoreConnectionSlots_VALUE = 10;

    /**
     * decodingFailed = 11
     */
    const decodingFailed_VALUE = 11;

    /**
     * characteristicNotFound = 12
     */
    const characteristicNotFound_VALUE = 12;

    /**
     * invalidRequest = 13
     */
    const invalidRequest_VALUE = 13;

    /**
     * gattError = 14
     */
    const gattError_VALUE = 14;

    /**
     * encryptionFailed = 15
     */
    const encryptionFailed_VALUE = 15;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $failureGeneric = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $success = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $deviceNotFound = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $apNotFound = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $actionTimeout = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $connectionAborted = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $authenticationFailed = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $notConnected = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $previousActionFailed = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $alreadyConnected = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $noMoreConnectionSlots = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $decodingFailed = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $characteristicNotFound = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $invalidRequest = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $gattError = null;

    /**
     * @var \aruba_telemetry\ActionStatus
     */
    protected static $encryptionFailed = null;

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function failureGeneric()
    {
        if (self::$failureGeneric !== null) {
            return self::$failureGeneric;
        }

        return self::$failureGeneric = new self('failureGeneric', self::failureGeneric_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function success()
    {
        if (self::$success !== null) {
            return self::$success;
        }

        return self::$success = new self('success', self::success_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function deviceNotFound()
    {
        if (self::$deviceNotFound !== null) {
            return self::$deviceNotFound;
        }

        return self::$deviceNotFound = new self('deviceNotFound', self::deviceNotFound_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function apNotFound()
    {
        if (self::$apNotFound !== null) {
            return self::$apNotFound;
        }

        return self::$apNotFound = new self('apNotFound', self::apNotFound_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function actionTimeout()
    {
        if (self::$actionTimeout !== null) {
            return self::$actionTimeout;
        }

        return self::$actionTimeout = new self('actionTimeout', self::actionTimeout_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function connectionAborted()
    {
        if (self::$connectionAborted !== null) {
            return self::$connectionAborted;
        }

        return self::$connectionAborted = new self('connectionAborted', self::connectionAborted_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function authenticationFailed()
    {
        if (self::$authenticationFailed !== null) {
            return self::$authenticationFailed;
        }

        return self::$authenticationFailed = new self('authenticationFailed', self::authenticationFailed_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function notConnected()
    {
        if (self::$notConnected !== null) {
            return self::$notConnected;
        }

        return self::$notConnected = new self('notConnected', self::notConnected_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function previousActionFailed()
    {
        if (self::$previousActionFailed !== null) {
            return self::$previousActionFailed;
        }

        return self::$previousActionFailed = new self('previousActionFailed', self::previousActionFailed_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function alreadyConnected()
    {
        if (self::$alreadyConnected !== null) {
            return self::$alreadyConnected;
        }

        return self::$alreadyConnected = new self('alreadyConnected', self::alreadyConnected_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function noMoreConnectionSlots()
    {
        if (self::$noMoreConnectionSlots !== null) {
            return self::$noMoreConnectionSlots;
        }

        return self::$noMoreConnectionSlots = new self('noMoreConnectionSlots', self::noMoreConnectionSlots_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function decodingFailed()
    {
        if (self::$decodingFailed !== null) {
            return self::$decodingFailed;
        }

        return self::$decodingFailed = new self('decodingFailed', self::decodingFailed_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function characteristicNotFound()
    {
        if (self::$characteristicNotFound !== null) {
            return self::$characteristicNotFound;
        }

        return self::$characteristicNotFound = new self('characteristicNotFound', self::characteristicNotFound_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function invalidRequest()
    {
        if (self::$invalidRequest !== null) {
            return self::$invalidRequest;
        }

        return self::$invalidRequest = new self('invalidRequest', self::invalidRequest_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function gattError()
    {
        if (self::$gattError !== null) {
            return self::$gattError;
        }

        return self::$gattError = new self('gattError', self::gattError_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionStatus
     */
    public static function encryptionFailed()
    {
        if (self::$encryptionFailed !== null) {
            return self::$encryptionFailed;
        }

        return self::$encryptionFailed = new self('encryptionFailed', self::encryptionFailed_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\ActionStatus
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::failureGeneric();
            case 1: return self::success();
            case 2: return self::deviceNotFound();
            case 3: return self::apNotFound();
            case 4: return self::actionTimeout();
            case 5: return self::connectionAborted();
            case 6: return self::authenticationFailed();
            case 7: return self::notConnected();
            case 8: return self::previousActionFailed();
            case 9: return self::alreadyConnected();
            case 10: return self::noMoreConnectionSlots();
            case 11: return self::decodingFailed();
            case 12: return self::characteristicNotFound();
            case 13: return self::invalidRequest();
            case 14: return self::gattError();
            case 15: return self::encryptionFailed();
            default: return null;
        }
    }


}

