<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-types.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.ActionType
 */
class ActionType extends \Protobuf\Enum
{

    /**
     * bleConnect = 0
     */
    const bleConnect_VALUE = 0;

    /**
     * bleDisconnect = 1
     */
    const bleDisconnect_VALUE = 1;

    /**
     * gattRead = 2
     */
    const gattRead_VALUE = 2;

    /**
     * gattWrite = 3
     */
    const gattWrite_VALUE = 3;

    /**
     * gattWriteWithResponse = 4
     */
    const gattWriteWithResponse_VALUE = 4;

    /**
     * gattNotification = 5
     */
    const gattNotification_VALUE = 5;

    /**
     * gattIndication = 6
     */
    const gattIndication_VALUE = 6;

    /**
     * bleAuthenticate = 7
     */
    const bleAuthenticate_VALUE = 7;

    /**
     * bleEncrypt = 8
     */
    const bleEncrypt_VALUE = 8;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $bleConnect = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $bleDisconnect = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $gattRead = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $gattWrite = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $gattWriteWithResponse = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $gattNotification = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $gattIndication = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $bleAuthenticate = null;

    /**
     * @var \aruba_telemetry\ActionType
     */
    protected static $bleEncrypt = null;

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function bleConnect()
    {
        if (self::$bleConnect !== null) {
            return self::$bleConnect;
        }

        return self::$bleConnect = new self('bleConnect', self::bleConnect_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function bleDisconnect()
    {
        if (self::$bleDisconnect !== null) {
            return self::$bleDisconnect;
        }

        return self::$bleDisconnect = new self('bleDisconnect', self::bleDisconnect_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function gattRead()
    {
        if (self::$gattRead !== null) {
            return self::$gattRead;
        }

        return self::$gattRead = new self('gattRead', self::gattRead_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function gattWrite()
    {
        if (self::$gattWrite !== null) {
            return self::$gattWrite;
        }

        return self::$gattWrite = new self('gattWrite', self::gattWrite_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function gattWriteWithResponse()
    {
        if (self::$gattWriteWithResponse !== null) {
            return self::$gattWriteWithResponse;
        }

        return self::$gattWriteWithResponse = new self('gattWriteWithResponse', self::gattWriteWithResponse_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function gattNotification()
    {
        if (self::$gattNotification !== null) {
            return self::$gattNotification;
        }

        return self::$gattNotification = new self('gattNotification', self::gattNotification_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function gattIndication()
    {
        if (self::$gattIndication !== null) {
            return self::$gattIndication;
        }

        return self::$gattIndication = new self('gattIndication', self::gattIndication_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function bleAuthenticate()
    {
        if (self::$bleAuthenticate !== null) {
            return self::$bleAuthenticate;
        }

        return self::$bleAuthenticate = new self('bleAuthenticate', self::bleAuthenticate_VALUE);
    }

    /**
     * @return \aruba_telemetry\ActionType
     */
    public static function bleEncrypt()
    {
        if (self::$bleEncrypt !== null) {
            return self::$bleEncrypt;
        }

        return self::$bleEncrypt = new self('bleEncrypt', self::bleEncrypt_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\ActionType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::bleConnect();
            case 1: return self::bleDisconnect();
            case 2: return self::gattRead();
            case 3: return self::gattWrite();
            case 4: return self::gattWriteWithResponse();
            case 5: return self::gattNotification();
            case 6: return self::gattIndication();
            case 7: return self::bleAuthenticate();
            case 8: return self::bleEncrypt();
            default: return null;
        }
    }


}

