<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-sb-action.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.AuthenticationMethod
 */
class AuthenticationMethod extends \Protobuf\Enum
{

    /**
     * none = 0
     */
    const none_VALUE = 0;

    /**
     * passkey = 1
     */
    const passkey_VALUE = 1;

    /**
     * oob = 2
     */
    const oob_VALUE = 2;

    /**
     * lescNone = 3
     */
    const lescNone_VALUE = 3;

    /**
     * lescPasskey = 4
     */
    const lescPasskey_VALUE = 4;

    /**
     * lescOob = 5
     */
    const lescOob_VALUE = 5;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $none = null;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $passkey = null;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $oob = null;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $lescNone = null;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $lescPasskey = null;

    /**
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected static $lescOob = null;

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function none()
    {
        if (self::$none !== null) {
            return self::$none;
        }

        return self::$none = new self('none', self::none_VALUE);
    }

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function passkey()
    {
        if (self::$passkey !== null) {
            return self::$passkey;
        }

        return self::$passkey = new self('passkey', self::passkey_VALUE);
    }

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function oob()
    {
        if (self::$oob !== null) {
            return self::$oob;
        }

        return self::$oob = new self('oob', self::oob_VALUE);
    }

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function lescNone()
    {
        if (self::$lescNone !== null) {
            return self::$lescNone;
        }

        return self::$lescNone = new self('lescNone', self::lescNone_VALUE);
    }

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function lescPasskey()
    {
        if (self::$lescPasskey !== null) {
            return self::$lescPasskey;
        }

        return self::$lescPasskey = new self('lescPasskey', self::lescPasskey_VALUE);
    }

    /**
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function lescOob()
    {
        if (self::$lescOob !== null) {
            return self::$lescOob;
        }

        return self::$lescOob = new self('lescOob', self::lescOob_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::none();
            case 1: return self::passkey();
            case 2: return self::oob();
            case 3: return self::lescNone();
            case 4: return self::lescPasskey();
            case 5: return self::lescOob();
            default: return null;
        }
    }


}

