<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-sb-action.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.Authentication
 */
class Authentication extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * method optional enum = 1
     *
     * @var \aruba_telemetry\AuthenticationMethod
     */
    protected $method = null;

    /**
     * bonding optional bool = 2
     *
     * @var bool
     */
    protected $bonding = null;

    /**
     * passkey optional string = 3
     *
     * @var string
     */
    protected $passkey = null;

    /**
     * keyOob optional bytes = 4
     *
     * @var \Protobuf\Stream
     */
    protected $keyOob = null;

    /**
     * keyOwn optional bytes = 5
     *
     * @var \Protobuf\Stream
     */
    protected $keyOwn = null;

    /**
     * Check if 'method' has a value
     *
     * @return bool
     */
    public function hasMethod()
    {
        return $this->method !== null;
    }

    /**
     * Get 'method' value
     *
     * @return \aruba_telemetry\AuthenticationMethod
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Set 'method' value
     *
     * @param \aruba_telemetry\AuthenticationMethod $value
     */
    public function setMethod(\aruba_telemetry\AuthenticationMethod $value = null)
    {
        $this->method = $value;
    }

    /**
     * Check if 'bonding' has a value
     *
     * @return bool
     */
    public function hasBonding()
    {
        return $this->bonding !== null;
    }

    /**
     * Get 'bonding' value
     *
     * @return bool
     */
    public function getBonding()
    {
        return $this->bonding;
    }

    /**
     * Set 'bonding' value
     *
     * @param bool $value
     */
    public function setBonding($value = null)
    {
        $this->bonding = $value;
    }

    /**
     * Check if 'passkey' has a value
     *
     * @return bool
     */
    public function hasPasskey()
    {
        return $this->passkey !== null;
    }

    /**
     * Get 'passkey' value
     *
     * @return string
     */
    public function getPasskey()
    {
        return $this->passkey;
    }

    /**
     * Set 'passkey' value
     *
     * @param string $value
     */
    public function setPasskey($value = null)
    {
        $this->passkey = $value;
    }

    /**
     * Check if 'keyOob' has a value
     *
     * @return bool
     */
    public function hasKeyOob()
    {
        return $this->keyOob !== null;
    }

    /**
     * Get 'keyOob' value
     *
     * @return \Protobuf\Stream
     */
    public function getKeyOob()
    {
        return $this->keyOob;
    }

    /**
     * Set 'keyOob' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setKeyOob($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->keyOob = $value;
    }

    /**
     * Check if 'keyOwn' has a value
     *
     * @return bool
     */
    public function hasKeyOwn()
    {
        return $this->keyOwn !== null;
    }

    /**
     * Get 'keyOwn' value
     *
     * @return \Protobuf\Stream
     */
    public function getKeyOwn()
    {
        return $this->keyOwn;
    }

    /**
     * Set 'keyOwn' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setKeyOwn($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->keyOwn = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'method' => null,
            'bonding' => null,
            'passkey' => null,
            'keyOob' => null,
            'keyOwn' => null
        ], $values);

        $message->setMethod($values['method']);
        $message->setBonding($values['bonding']);
        $message->setPasskey($values['passkey']);
        $message->setKeyOob($values['keyOob']);
        $message->setKeyOwn($values['keyOwn']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'Authentication',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'method',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.aruba_telemetry.AuthenticationMethod'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'bonding',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'passkey',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'keyOob',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'keyOwn',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->method !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->method->value());
        }

        if ($this->bonding !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeBool($stream, $this->bonding);
        }

        if ($this->passkey !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeString($stream, $this->passkey);
        }

        if ($this->keyOob !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeByteStream($stream, $this->keyOob);
        }

        if ($this->keyOwn !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeByteStream($stream, $this->keyOwn);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->method = \aruba_telemetry\AuthenticationMethod::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->bonding = $reader->readBool($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->passkey = $reader->readString($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->keyOob = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->keyOwn = $reader->readByteStream($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->method !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->method->value());
        }

        if ($this->bonding !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->passkey !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->passkey);
        }

        if ($this->keyOob !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->keyOob);
        }

        if ($this->keyOwn !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->keyOwn);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->method = null;
        $this->bonding = null;
        $this->passkey = null;
        $this->keyOob = null;
        $this->keyOwn = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\Authentication) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->method = ($message->method !== null) ? $message->method : $this->method;
        $this->bonding = ($message->bonding !== null) ? $message->bonding : $this->bonding;
        $this->passkey = ($message->passkey !== null) ? $message->passkey : $this->passkey;
        $this->keyOob = ($message->keyOob !== null) ? $message->keyOob : $this->keyOob;
        $this->keyOwn = ($message->keyOwn !== null) ? $message->keyOwn : $this->keyOwn;
    }


}

