<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-ble-data.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.BleData
 */
class BleData extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * mac optional bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $mac = null;

    /**
     * frameType optional enum = 2
     *
     * @var \aruba_telemetry\BleFrameType
     */
    protected $frameType = null;

    /**
     * data optional bytes = 3
     *
     * @var \Protobuf\Stream
     */
    protected $data = null;

    /**
     * rssi optional sint32 = 4
     *
     * @var int
     */
    protected $rssi = null;

    /**
     * Check if 'mac' has a value
     *
     * @return bool
     */
    public function hasMac()
    {
        return $this->mac !== null;
    }

    /**
     * Get 'mac' value
     *
     * @return \Protobuf\Stream
     */
    public function getMac()
    {
        return $this->mac;
    }

    /**
     * Set 'mac' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setMac($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->mac = $value;
    }

    /**
     * Check if 'frameType' has a value
     *
     * @return bool
     */
    public function hasFrameType()
    {
        return $this->frameType !== null;
    }

    /**
     * Get 'frameType' value
     *
     * @return \aruba_telemetry\BleFrameType
     */
    public function getFrameType()
    {
        return $this->frameType;
    }

    /**
     * Set 'frameType' value
     *
     * @param \aruba_telemetry\BleFrameType $value
     */
    public function setFrameType(\aruba_telemetry\BleFrameType $value = null)
    {
        $this->frameType = $value;
    }

    /**
     * Check if 'data' has a value
     *
     * @return bool
     */
    public function hasData()
    {
        return $this->data !== null;
    }

    /**
     * Get 'data' value
     *
     * @return \Protobuf\Stream
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Set 'data' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setData($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->data = $value;
    }

    /**
     * Check if 'rssi' has a value
     *
     * @return bool
     */
    public function hasRssi()
    {
        return $this->rssi !== null;
    }

    /**
     * Get 'rssi' value
     *
     * @return int
     */
    public function getRssi()
    {
        return $this->rssi;
    }

    /**
     * Set 'rssi' value
     *
     * @param int $value
     */
    public function setRssi($value = null)
    {
        $this->rssi = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'mac' => null,
            'frameType' => null,
            'data' => null,
            'rssi' => null
        ], $values);

        $message->setMac($values['mac']);
        $message->setFrameType($values['frameType']);
        $message->setData($values['data']);
        $message->setRssi($values['rssi']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'BleData',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'mac',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'frameType',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.aruba_telemetry.BleFrameType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'data',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'rssi',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_SINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->mac !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->mac);
        }

        if ($this->frameType !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->frameType->value());
        }

        if ($this->data !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeByteStream($stream, $this->data);
        }

        if ($this->rssi !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeZigzag32($stream, $this->rssi);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->mac = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->frameType = \aruba_telemetry\BleFrameType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->data = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 17);

                $this->rssi = $reader->readZigzag($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->mac !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->mac);
        }

        if ($this->frameType !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->frameType->value());
        }

        if ($this->data !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->data);
        }

        if ($this->rssi !== null) {
            $size += 1;
            $size += $calculator->computeZigzag32Size($this->rssi);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->mac = null;
        $this->frameType = null;
        $this->data = null;
        $this->rssi = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\BleData) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->mac = ($message->mac !== null) ? $message->mac : $this->mac;
        $this->frameType = ($message->frameType !== null) ? $message->frameType : $this->frameType;
        $this->data = ($message->data !== null) ? $message->data : $this->data;
        $this->rssi = ($message->rssi !== null) ? $message->rssi : $this->rssi;
    }


}

