<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-telemetry.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.EddyURL
 */
class EddyURL extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * prefix required uint32 = 1
     *
     * @var int
     */
    protected $prefix = null;

    /**
     * encodedUrl required bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $encodedUrl = null;

    /**
     * Check if 'prefix' has a value
     *
     * @return bool
     */
    public function hasPrefix()
    {
        return $this->prefix !== null;
    }

    /**
     * Get 'prefix' value
     *
     * @return int
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Set 'prefix' value
     *
     * @param int $value
     */
    public function setPrefix($value)
    {
        $this->prefix = $value;
    }

    /**
     * Check if 'encodedUrl' has a value
     *
     * @return bool
     */
    public function hasEncodedUrl()
    {
        return $this->encodedUrl !== null;
    }

    /**
     * Get 'encodedUrl' value
     *
     * @return \Protobuf\Stream
     */
    public function getEncodedUrl()
    {
        return $this->encodedUrl;
    }

    /**
     * Set 'encodedUrl' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setEncodedUrl($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->encodedUrl = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['prefix'])) {
            throw new \InvalidArgumentException('Field "prefix" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['encodedUrl'])) {
            throw new \InvalidArgumentException('Field "encodedUrl" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
        ], $values);

        $message->setPrefix($values['prefix']);
        $message->setEncodedUrl($values['encodedUrl']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'EddyURL',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'prefix',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'encodedUrl',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->prefix === null) {
            throw new \UnexpectedValueException('Field "\\aruba_telemetry\\EddyURL#prefix" (tag 1) is required but has no value.');
        }

        if ($this->encodedUrl === null) {
            throw new \UnexpectedValueException('Field "\\aruba_telemetry\\EddyURL#encodedUrl" (tag 2) is required but has no value.');
        }

        if ($this->prefix !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->prefix);
        }

        if ($this->encodedUrl !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeByteStream($stream, $this->encodedUrl);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->prefix = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->encodedUrl = $reader->readByteStream($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->prefix !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->prefix);
        }

        if ($this->encodedUrl !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->encodedUrl);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->prefix = null;
        $this->encodedUrl = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\EddyURL) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->prefix = ($message->prefix !== null) ? $message->prefix : $this->prefix;
        $this->encodedUrl = ($message->encodedUrl !== null) ? $message->encodedUrl : $this->encodedUrl;
    }


}

