<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-ap-health-update.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.IotRadioFirmware
 */
class IotRadioFirmware extends \Protobuf\Enum
{

    /**
     * arubaDefault = 0
     */
    const arubaDefault_VALUE = 0;

    /**
     * @var \aruba_telemetry\IotRadioFirmware
     */
    protected static $arubaDefault = null;

    /**
     * @return \aruba_telemetry\IotRadioFirmware
     */
    public static function arubaDefault()
    {
        if (self::$arubaDefault !== null) {
            return self::$arubaDefault;
        }

        return self::$arubaDefault = new self('arubaDefault', self::arubaDefault_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\IotRadioFirmware
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::arubaDefault();
            default: return null;
        }
    }


}

