<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-ap-health-update.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.IotRadioType
 */
class IotRadioType extends \Protobuf\Enum
{

    /**
     * gen1 = 0
     */
    const gen1_VALUE = 0;

    /**
     * gen2 = 1
     */
    const gen2_VALUE = 1;

    /**
     * @var \aruba_telemetry\IotRadioType
     */
    protected static $gen1 = null;

    /**
     * @var \aruba_telemetry\IotRadioType
     */
    protected static $gen2 = null;

    /**
     * @return \aruba_telemetry\IotRadioType
     */
    public static function gen1()
    {
        if (self::$gen1 !== null) {
            return self::$gen1;
        }

        return self::$gen1 = new self('gen1', self::gen1_VALUE);
    }

    /**
     * @return \aruba_telemetry\IotRadioType
     */
    public static function gen2()
    {
        if (self::$gen2 !== null) {
            return self::$gen2;
        }

        return self::$gen2 = new self('gen2', self::gen2_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\IotRadioType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::gen1();
            case 1: return self::gen2();
            default: return null;
        }
    }


}

