<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-ap-health-update.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.IotRadio
 */
class IotRadio extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * mac optional bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $mac = null;

    /**
     * hardware optional enum = 2
     *
     * @var \aruba_telemetry\IotRadioType
     */
    protected $hardware = null;

    /**
     * firmware optional enum = 3
     *
     * @var \aruba_telemetry\IotRadioFirmware
     */
    protected $firmware = null;

    /**
     * health optional enum = 4
     *
     * @var \aruba_telemetry\HealthStatus
     */
    protected $health = null;

    /**
     * external optional bool = 5
     *
     * @var bool
     */
    protected $external = null;

    /**
     * Check if 'mac' has a value
     *
     * @return bool
     */
    public function hasMac()
    {
        return $this->mac !== null;
    }

    /**
     * Get 'mac' value
     *
     * @return \Protobuf\Stream
     */
    public function getMac()
    {
        return $this->mac;
    }

    /**
     * Set 'mac' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setMac($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->mac = $value;
    }

    /**
     * Check if 'hardware' has a value
     *
     * @return bool
     */
    public function hasHardware()
    {
        return $this->hardware !== null;
    }

    /**
     * Get 'hardware' value
     *
     * @return \aruba_telemetry\IotRadioType
     */
    public function getHardware()
    {
        return $this->hardware;
    }

    /**
     * Set 'hardware' value
     *
     * @param \aruba_telemetry\IotRadioType $value
     */
    public function setHardware(\aruba_telemetry\IotRadioType $value = null)
    {
        $this->hardware = $value;
    }

    /**
     * Check if 'firmware' has a value
     *
     * @return bool
     */
    public function hasFirmware()
    {
        return $this->firmware !== null;
    }

    /**
     * Get 'firmware' value
     *
     * @return \aruba_telemetry\IotRadioFirmware
     */
    public function getFirmware()
    {
        return $this->firmware;
    }

    /**
     * Set 'firmware' value
     *
     * @param \aruba_telemetry\IotRadioFirmware $value
     */
    public function setFirmware(\aruba_telemetry\IotRadioFirmware $value = null)
    {
        $this->firmware = $value;
    }

    /**
     * Check if 'health' has a value
     *
     * @return bool
     */
    public function hasHealth()
    {
        return $this->health !== null;
    }

    /**
     * Get 'health' value
     *
     * @return \aruba_telemetry\HealthStatus
     */
    public function getHealth()
    {
        return $this->health;
    }

    /**
     * Set 'health' value
     *
     * @param \aruba_telemetry\HealthStatus $value
     */
    public function setHealth(\aruba_telemetry\HealthStatus $value = null)
    {
        $this->health = $value;
    }

    /**
     * Check if 'external' has a value
     *
     * @return bool
     */
    public function hasExternal()
    {
        return $this->external !== null;
    }

    /**
     * Get 'external' value
     *
     * @return bool
     */
    public function getExternal()
    {
        return $this->external;
    }

    /**
     * Set 'external' value
     *
     * @param bool $value
     */
    public function setExternal($value = null)
    {
        $this->external = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'mac' => null,
            'hardware' => null,
            'firmware' => null,
            'health' => null,
            'external' => null
        ], $values);

        $message->setMac($values['mac']);
        $message->setHardware($values['hardware']);
        $message->setFirmware($values['firmware']);
        $message->setHealth($values['health']);
        $message->setExternal($values['external']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'IotRadio',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'mac',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'hardware',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.aruba_telemetry.IotRadioType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'firmware',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.aruba_telemetry.IotRadioFirmware'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'health',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'type_name' => '.aruba_telemetry.HealthStatus'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'external',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->mac !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->mac);
        }

        if ($this->hardware !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->hardware->value());
        }

        if ($this->firmware !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->firmware->value());
        }

        if ($this->health !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->health->value());
        }

        if ($this->external !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeBool($stream, $this->external);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->mac = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->hardware = \aruba_telemetry\IotRadioType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->firmware = \aruba_telemetry\IotRadioFirmware::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->health = \aruba_telemetry\HealthStatus::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->external = $reader->readBool($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->mac !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->mac);
        }

        if ($this->hardware !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->hardware->value());
        }

        if ($this->firmware !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->firmware->value());
        }

        if ($this->health !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->health->value());
        }

        if ($this->external !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->mac = null;
        $this->hardware = null;
        $this->firmware = null;
        $this->health = null;
        $this->external = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\IotRadio) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->mac = ($message->mac !== null) ? $message->mac : $this->mac;
        $this->hardware = ($message->hardware !== null) ? $message->hardware : $this->hardware;
        $this->firmware = ($message->firmware !== null) ? $message->firmware : $this->firmware;
        $this->health = ($message->health !== null) ? $message->health : $this->health;
        $this->external = ($message->external !== null) ? $message->external : $this->external;
    }


}

