<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-nb-serial-data.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.NbSerialData
 */
class NbSerialData extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * nbSerialPayload optional bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $nbSerialPayload = null;

    /**
     * nbDeviceId optional string = 2
     *
     * @var string
     */
    protected $nbDeviceId = null;

    /**
     * Check if 'nbSerialPayload' has a value
     *
     * @return bool
     */
    public function hasNbSerialPayload()
    {
        return $this->nbSerialPayload !== null;
    }

    /**
     * Get 'nbSerialPayload' value
     *
     * @return \Protobuf\Stream
     */
    public function getNbSerialPayload()
    {
        return $this->nbSerialPayload;
    }

    /**
     * Set 'nbSerialPayload' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setNbSerialPayload($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->nbSerialPayload = $value;
    }

    /**
     * Check if 'nbDeviceId' has a value
     *
     * @return bool
     */
    public function hasNbDeviceId()
    {
        return $this->nbDeviceId !== null;
    }

    /**
     * Get 'nbDeviceId' value
     *
     * @return string
     */
    public function getNbDeviceId()
    {
        return $this->nbDeviceId;
    }

    /**
     * Set 'nbDeviceId' value
     *
     * @param string $value
     */
    public function setNbDeviceId($value = null)
    {
        $this->nbDeviceId = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'nbSerialPayload' => null,
            'nbDeviceId' => null
        ], $values);

        $message->setNbSerialPayload($values['nbSerialPayload']);
        $message->setNbDeviceId($values['nbDeviceId']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'NbSerialData',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'nbSerialPayload',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'nbDeviceId',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->nbSerialPayload !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->nbSerialPayload);
        }

        if ($this->nbDeviceId !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->nbDeviceId);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->nbSerialPayload = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->nbDeviceId = $reader->readString($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->nbSerialPayload !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->nbSerialPayload);
        }

        if ($this->nbDeviceId !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->nbDeviceId);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->nbSerialPayload = null;
        $this->nbDeviceId = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\NbSerialData) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->nbSerialPayload = ($message->nbSerialPayload !== null) ? $message->nbSerialPayload : $this->nbSerialPayload;
        $this->nbDeviceId = ($message->nbDeviceId !== null) ? $message->nbDeviceId : $this->nbDeviceId;
    }


}

