<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-types.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf enum : aruba_telemetry.NbTopic
 */
class NbTopic extends \Protobuf\Enum
{

    /**
     * telemetry = 0
     */
    const telemetry_VALUE = 0;

    /**
     * actionResults = 1
     */
    const actionResults_VALUE = 1;

    /**
     * characteristics = 2
     */
    const characteristics_VALUE = 2;

    /**
     * bleData = 3
     */
    const bleData_VALUE = 3;

    /**
     * wifiData = 4
     */
    const wifiData_VALUE = 4;

    /**
     * deviceCount = 5
     */
    const deviceCount_VALUE = 5;

    /**
     * status = 6
     */
    const status_VALUE = 6;

    /**
     * zbNbData = 7
     */
    const zbNbData_VALUE = 7;

    /**
     * serialDataNb = 8
     */
    const serialDataNb_VALUE = 8;

    /**
     * apHealthUpdate = 9
     */
    const apHealthUpdate_VALUE = 9;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $telemetry = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $actionResults = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $characteristics = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $bleData = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $wifiData = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $deviceCount = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $status = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $zbNbData = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $serialDataNb = null;

    /**
     * @var \aruba_telemetry\NbTopic
     */
    protected static $apHealthUpdate = null;

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function telemetry()
    {
        if (self::$telemetry !== null) {
            return self::$telemetry;
        }

        return self::$telemetry = new self('telemetry', self::telemetry_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function actionResults()
    {
        if (self::$actionResults !== null) {
            return self::$actionResults;
        }

        return self::$actionResults = new self('actionResults', self::actionResults_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function characteristics()
    {
        if (self::$characteristics !== null) {
            return self::$characteristics;
        }

        return self::$characteristics = new self('characteristics', self::characteristics_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function bleData()
    {
        if (self::$bleData !== null) {
            return self::$bleData;
        }

        return self::$bleData = new self('bleData', self::bleData_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function wifiData()
    {
        if (self::$wifiData !== null) {
            return self::$wifiData;
        }

        return self::$wifiData = new self('wifiData', self::wifiData_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function deviceCount()
    {
        if (self::$deviceCount !== null) {
            return self::$deviceCount;
        }

        return self::$deviceCount = new self('deviceCount', self::deviceCount_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function status()
    {
        if (self::$status !== null) {
            return self::$status;
        }

        return self::$status = new self('status', self::status_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function zbNbData()
    {
        if (self::$zbNbData !== null) {
            return self::$zbNbData;
        }

        return self::$zbNbData = new self('zbNbData', self::zbNbData_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function serialDataNb()
    {
        if (self::$serialDataNb !== null) {
            return self::$serialDataNb;
        }

        return self::$serialDataNb = new self('serialDataNb', self::serialDataNb_VALUE);
    }

    /**
     * @return \aruba_telemetry\NbTopic
     */
    public static function apHealthUpdate()
    {
        if (self::$apHealthUpdate !== null) {
            return self::$apHealthUpdate;
        }

        return self::$apHealthUpdate = new self('apHealthUpdate', self::apHealthUpdate_VALUE);
    }

    /**
     * @param int $value
     * @return \aruba_telemetry\NbTopic
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::telemetry();
            case 1: return self::actionResults();
            case 2: return self::characteristics();
            case 3: return self::bleData();
            case 4: return self::wifiData();
            case 5: return self::deviceCount();
            case 6: return self::status();
            case 7: return self::zbNbData();
            case 8: return self::serialDataNb();
            case 9: return self::apHealthUpdate();
            default: return null;
        }
    }


}

