<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : aruba-iot-zb-types.proto
 */


namespace aruba_telemetry;

/**
 * Protobuf message : aruba_telemetry.ZbEPC
 */
class ZbEPC extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * endpoint optional uint32 = 1
     *
     * @var int
     */
    protected $endpoint = null;

    /**
     * profile_id optional uint32 = 2
     *
     * @var int
     */
    protected $profile_id = null;

    /**
     * cluster_id optional uint32 = 3
     *
     * @var int
     */
    protected $cluster_id = null;

    /**
     * Check if 'endpoint' has a value
     *
     * @return bool
     */
    public function hasEndpoint()
    {
        return $this->endpoint !== null;
    }

    /**
     * Get 'endpoint' value
     *
     * @return int
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Set 'endpoint' value
     *
     * @param int $value
     */
    public function setEndpoint($value = null)
    {
        $this->endpoint = $value;
    }

    /**
     * Check if 'profile_id' has a value
     *
     * @return bool
     */
    public function hasProfileId()
    {
        return $this->profile_id !== null;
    }

    /**
     * Get 'profile_id' value
     *
     * @return int
     */
    public function getProfileId()
    {
        return $this->profile_id;
    }

    /**
     * Set 'profile_id' value
     *
     * @param int $value
     */
    public function setProfileId($value = null)
    {
        $this->profile_id = $value;
    }

    /**
     * Check if 'cluster_id' has a value
     *
     * @return bool
     */
    public function hasClusterId()
    {
        return $this->cluster_id !== null;
    }

    /**
     * Get 'cluster_id' value
     *
     * @return int
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * Set 'cluster_id' value
     *
     * @param int $value
     */
    public function setClusterId($value = null)
    {
        $this->cluster_id = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'endpoint' => null,
            'profile_id' => null,
            'cluster_id' => null
        ], $values);

        $message->setEndpoint($values['endpoint']);
        $message->setProfileId($values['profile_id']);
        $message->setClusterId($values['cluster_id']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'ZbEPC',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'endpoint',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'profile_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'cluster_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->endpoint !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->endpoint);
        }

        if ($this->profile_id !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->profile_id);
        }

        if ($this->cluster_id !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->cluster_id);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->endpoint = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->profile_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->cluster_id = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->endpoint !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->endpoint);
        }

        if ($this->profile_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->profile_id);
        }

        if ($this->cluster_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->cluster_id);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->endpoint = null;
        $this->profile_id = null;
        $this->cluster_id = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \aruba_telemetry\ZbEPC) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->endpoint = ($message->endpoint !== null) ? $message->endpoint : $this->endpoint;
        $this->profile_id = ($message->profile_id !== null) ? $message->profile_id : $this->profile_id;
        $this->cluster_id = ($message->cluster_id !== null) ? $message->cluster_id : $this->cluster_id;
    }


}

